name: My first pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - dev
      - main

jobs:
  firstJob:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello world
        run: echo "Hello World"
